### ISSUE TITLE
Help needed with overriding default colors.

### ISSUE THREAD

**Issue by Tibor5** [Fabiokleis/emacs-kanagawa-theme#1]
Hello!

Thank you for porting Kanagawa to Emacs, I missed it from Neovim :)

I am having trouble overriding the default `sumi-ink-1b` color. I might be doing something wrong, could you please help me?

This is my setup (I'm using elpaca, it allows specifying recipe within `:ensure`):  

```
(use-package kanagawa-theme
  :ensure (:host github :repo "Fabiokleis/emacs-kanagawa-theme")
  :demand t
  :custom
  (kanagawa-theme-comment-italic)
  (kanagawa-theme-custom-colors '((sumi-ink-1b . "#0A0E14")))
  :config
  (load-theme 'kanagawa t)
```

From what I was able to understand by reading the source code, the `kanagawa-theme-custom-colors` accepts an alist, and I believe that I have the syntax correct since Emacs isn't complaining.

Thank you

**Comment by Fabiokleis** [comment]
> Hello!
> 
> Thank you for porting Kanagawa to Emacs, I missed it from Neovim :)
> 
> I am having trouble overriding the default `sumi-ink-1b` color. I might be doing something wrong, could you please help me?
> 
> This is my setup (I'm using elpaca, it allows specifying recipe within `:ensure`):
> 
> ```
> (use-package kanagawa-theme
>   :ensure (:host github :repo "Fabiokleis/emacs-kanagawa-theme")
>   :demand t
>   :custom
>   (kanagawa-theme-comment-italic)
>   (kanagawa-theme-custom-colors '((sumi-ink-1b . "#0A0E14")))
>   :config
>   (load-theme 'kanagawa t)
> ```
> 
> From what I was able to understand by reading the source code, the `kanagawa-theme-custom-colors` accepts an alist, and I believe that I have the syntax correct since Emacs isn't complaining.
> 
> Thank you

you are calling `kanagawa-theme-custom-colors` like a function, but actually it is a variable, I think you can just use setq like this:
```el
  (setq kanagawa-theme-custom-colors '((sumi-ink-1b . "#0A0E14"))) 
```

**Comment by Tibor5** [comment]
I tried setq-ing it like that both under `:config` and `:custom`, but nothing changed.

```
(use-package kanagawa-theme
  :ensure (:host github :repo "Fabiokleis/emacs-kanagawa-theme")
  :config
  (setq kanagawa-theme-custom-colors '((sumi-ink-1b . "#0A0E14")
                                       (sumi-ink-1 . "#0A0E14")))
  (load-theme 'kanagawa t))
```

My goal is to override the color that is the main background color. I assume that's the 'default' one, which uses `sumi-ink-1b`, that's why I'm attempting to do it like so. Is there another way?

**Comment by Fabiokleis** [comment]
> I tried setq-ing it like that both under `:config` and `:custom`, but nothing changed.
> 
> ```
> (use-package kanagawa-theme
>   :ensure (:host github :repo "Fabiokleis/emacs-kanagawa-theme")
>   :config
>   (setq kanagawa-theme-custom-colors '((sumi-ink-1b . "#0A0E14")
>                                        (sumi-ink-1 . "#0A0E14")))
>   (load-theme 'kanagawa t))
> ```
> 
> My goal is to override the color that is the main background color. I assume that's the 'default' one, which uses `sumi-ink-1b`, that's why I'm attempting to do it like so. Is there another way?

you can use `customize-option` command, I'm not sure if gonna work. I don't know a lot of elisp and I simply copy pasted this theme, sorry..

**Comment by Tibor5** [comment]
I see. No problems, I'll figure it out.

Thank you for your help.

**Comment by Fabiokleis** [comment]
@Tibor5  Sorry for reopening this issue but I guess I found a way to customize kanagawa.
```elisp
(use-package kanagawa-theme
  :load-path "~/.emacs.d/themes"
  :preface
  (setq kanagawa-theme-custom-colors '((sumi-ink-1b . "#000000")))
  :config
  (load-theme 'kanagawa t))
```
I put on my init.el and after reopening emacs it worked. I guess there is a problem when you load the package. Please try to load from a file and make sure you didn't have kanagawa installed.

**Comment by Fabiokleis** [comment]
> @Tibor5 Sorry for reopening this issue but I guess I found a way to customize kanagawa.
> 
> ```emacs-lisp
> (use-package kanagawa-theme
>   :load-path "~/.emacs.d/themes"
>   :preface
>   (setq kanagawa-theme-custom-colors '((sumi-ink-1b . "#000000")))
>   :config
>   (load-theme 'kanagawa t))
> ```
> 
> I put on my init.el and after reopening emacs it worked. I guess there is a problem when you load the package. Please try to load from a file and make sure you didn't have kanagawa installed.

@Tibor5  I have fixed the customization issue, now you can set kanagawa-theme-custom-colors like this. I'm gonna solve lint warnings and you should install kanagawa-theme from MELPA soon.
```elisp
(use-package kanagawa-theme
  :load-path "~/git_hub/emacs-kanagawa-theme/"
  :preface
  (setq kanagawa-theme-custom-colors '((sumi-ink-1b "#0A0E14")))
  :config
  (load-theme 'kanagawa t))
```

**Comment by Tibor5** [comment]
That's great, I'll test it when I get to the computer. Thank you for your help!
